gems:                [jekyll-paginate]

# Permalinks
permalink:           pretty
relative_permalinks: false

# Setup
title:               Chriskuei
tagline:             'Keep calm and code on'
description:         'Life style = Code + Fitness + Books'
url:                 http://blog.chriskuei.cn
baseurl:             /
paginate:            3

# About/contact
author:
  name:              'Chriskuei'
  url:               https://weibo.com/chenjiangui
  email:             chenjiangui@outlook.com

# Custom vars
version:             1.0.0

contact:
  Github:            https://github.com/chriskuei
  Weibo:             https://weibo.com/chenjiangui
  Zhihu:             https://zhihu.com/people/chenjiangui
